name: Deploy to aws

on:
 push:
  branches:
   - main

jobs:
 deploy:
  name: Build Deploy
  runs-on: ubuntu-latest

  steps:
  - name: Checkout repository
    uses: actions/checkout@v4
  
  - name: Python
    uses: actions/setup-python@v5
    with:
     python-version: "3.9"

  - name: requirements
    run: |
     python -m pip install --upgrade pip
     pip install -r requirements.txt

  - name: test
    env:
     PYTHONPATH: .
    run: pytest
 
  - name: aws github user credential
    uses: aws-actions/configure-aws-credentials@v4
    with:
     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     aws-region: ${{ secrets.AWS_REGION }} 
  
  - name: verify aws user
    run: |
     aws sts get-caller-identity
 
  - name: ECR login
    uses: aws-actions/amazon-ecr-login@v2
  
  - name: docker image
    run: |
     docker build \
      -t ${{ secrets.ECR_REPOSITORY }}:latest \
      . 
